- hosts: localhost
  sudo: yes
  tasks:
      - name: Install ansible dependencies
        command: apt-get install -y python-apt python-psycopg2

      - name: Add archive.opinsys.fi
        apt_repository: repo='deb http://archive.opinsys.fi/git-trusty trusty main restricted universe multiverse' state=present update_cache=yes

      - name: install postgresql
        apt: pkg=postgresql state=present

      - name: Install git
        apt: pkg=git state=present force=yes

      - name: Install browsers
        action: apt pkg={{item}} state=present
        with_items:
          - firefox
          - chromium-browser

      - name: Install xvfb for headless testing
        apt: pkg=xvfb state=present

      - name: Install node.js
        apt: pkg=nodejs-bundle state=present force=yes

      - name: Install build tools
        apt: pkg=build-essential  state=present

      - name: Create databases
        sudo_user: postgres
        action: postgresql_db name={{item}}
                              encoding='UTF-8'
                              lc_collate='en_US.UTF-8'
                              lc_ctype='en_US.UTF-8'
        with_items:
          - puavo-ticket
          - puavo-ticket-test


      - name: Add Postgresql user
        sudo_user: postgres
        postgresql_user: name=puavo-ticket password=password role_attr_flags=LOGIN

      - name: Grant permissions to postgres user for puavo-ticket databases
        sudo_user: postgres
        action: postgresql_privs db={{item}}
                                 privs=ALL
                                 type=database
                                 roles=puavo-ticket
        with_items:
          - puavo-ticket
          - puavo-ticket-test


      - name: Install Puavo dependencies
        command: apt-get install -y --force-yes puavo-standalone ruby1.9.1 ruby1.9.1-dev libxml2-dev libxslt-dev libsqlite3-dev libmagickwand-dev ldap-utils libpq-dev libssl-dev build-essential libopenssl-ruby xpdf-utils git libreadline6-dev libxml2-dev libxslt1-dev libpq-dev libmagickwand-dev libsqlite3-dev ruby-bundler puavo-client nodejs-bundle puavo-ca-rails redis-server aptirepo-upload puavo-devscripts

      - name: LDAP-configuration
        command: puavo-init-standalone --unsafe-passwords opinsys.net

      - name: Create organisatios for test and development
        command: puavo-add-new-organisation --yes {{ item.organisation }} --username {{ item.username }} --password {{ item.password }} --given-name {{ item.given-name }} --surname {{ item.surname }}
        creates: /var/lib/ldap/dc=edu,dc=hogwarts,dc=fi
        with_items:
          - { organisation: "hogwarts",
              username: "albus",
              password: "albus",
              given-name: "Albus",
              surname: "Dumbledore" }
          - { organisation: "example",
              username: "cucumber",
              password: "cucumber",
              given-name: "cucumber",
              surname: "cucumber" }
          - { organisation: "anotherorg",
              username: "admin",
              password: "admin",
              given-name: "Admin",
              surname: "Administrator" }

      - name: Clone puavo-user repository
        git: repo=git://github.com/opinsys/puavo-users.git
        dest={{ code_dest }}/puavo-users

      - name: puavo-web, Install Ruby gems, node modules and build assets.
        command: make
          chdir={{ code_dest }}/puavo-users

      - name: puavo-web configuration
        command: bundle exec rake puavo:configuration
          chdir={{ code_dest }}/puavo-users

      - name: puavo-rest, Install Ruby gems etc.
        command: make dev-install
          chdir={{ code_dest }}/puavo-users/rest
