- hosts: localhost
  sudo: yes
  tasks:
      - name: Add archive.opinsys.fi
        apt_repository: repo='deb http://archive.opinsys.fi/git-trusty trusty main restricted universe multiverse' state=present update_cache=yes

      - name: install postgresql
        apt: pkg=postgresql state=present

      - name: Install python postgresql package for adding users from Ansible
        apt: pkg=python-psycopg2 state=present

      - name: Install node.js
        apt: pkg=nodejs-bundle state=present force=yes

      - name: Install build tools
        apt: pkg=build-essential  state=present

      - name: Add testing database for puavo-ticket
        sudo_user: postgres
        postgresql_db: name=puavo-ticket-test
                       encoding='UTF-8'
                       lc_collate='en_US.UTF-8'
                       lc_ctype='en_US.UTF-8'

      - name: Add Postgresql user
        sudo_user: postgres
        postgresql_user: name=puavo password=password db=puavo-ticket-test role_attr_flags=LOGIN

