- hosts: localhost
  sudo: yes
  vars:
    puavo_ca_port: 3000
    puavo_web_port: 3001
    puavo_ticket_port: 3002
    puavo_rest_port: 9292
    archive_server: archive.opinsys.fi
  roles:
    - selenium
    - puavo-ldap
    - puavo-ticket
