- hosts: localhost
  sudo: yes
  tasks:
      - name: Install ansible dependencies
        action: apt pkg={{item}} state=present
        with_items:
          - python-apt
          - python-psycopg2

      - name: Add archive.opinsys.fi
        apt_repository: repo='deb http://archive.opinsys.fi/git-trusty trusty main restricted universe multiverse' state=present update_cache=yes

      - name: install postgresql
        apt: pkg=postgresql state=present

      - name: Install git
        apt: pkg=git state=present force=yes

      - name: Install browsers
        action: apt pkg={{item}} state=present
        with_items:
          - firefox
          - chromium-browser

      - name: Install xvfb for headless testing
        apt: pkg=xvfb state=present

      - name: Install node.js
        apt: pkg=nodejs-bundle state=present force=yes

      - name: Install build tools
        apt: pkg=build-essential  state=present

      - name: Create databases
        sudo_user: postgres
        action: postgresql_db name={{item}}
                              encoding='UTF-8'
                              lc_collate='en_US.UTF-8'
                              lc_ctype='en_US.UTF-8'
        with_items:
          - puavo-ticket
          - puavo-ticket-test


      - name: Add Postgresql user
        sudo_user: postgres
        postgresql_user: name=puavo-ticket password=password role_attr_flags=LOGIN

      - name: Grant permissions to postgres user for puavo-ticket databases
        sudo_user: postgres
        action: postgresql_privs db={{item}}
                                 privs=ALL
                                 type=database
                                 roles=puavo-ticket
        with_items:
          - puavo-ticket
          - puavo-ticket-test


