example:
  name: Example Organisation
  host: www.example.com
  ldap_host: <%= @hostname %>
  ldap_base: dc=edu,dc=example,dc=fi
  owner: cucumber
  owner_pw: cucumber
  locale: en

anotherorg:
  name: Another Organisation
  host: anotherorg.example.net
  ldap_host: <%= @hostname %>
  ldap_base: dc=edu,dc=anotherorg,dc=fi
  owner: admin
  owner_pw: admin
  locale: en

heroes:
  name: Super Heroes Organisation
  host: heroes.example.net
  ldap_host: <%= @hostname %>
  ldap_base: dc=edu,dc=heroes,dc=fi
  owner: admin
  owner_pw: admin
  locale: en

example2:
  name: Example Organisation
  host: 127.0.0.1
  ldap_host: jokor-puavo.example.net
  ldap_base: dc=edu,dc=example,dc=fi
  owner: cucumber
  owner_pw: cucumber
  locale: en

# Default organisation configurations.
# This is used to if browser request host not matched with other settings.
hogwarts:
  name: Hogwarts
  host: *
  ldap_host: <%= @hostname %>
  ldap_base: dc=edu,dc=hogwarts,dc=fi
  locale: en
